development:
  adapter: mysql2
  database: documentcard_dev
  host: localhost
  username: root
  password: 

test:
  adapter: mysql2
  database: documentcard_test
  host: localhost
  username: root
  password:
